name: Verifiable Presentation POC
on: [push]
jobs:
  build:
    name: Build, lint, audit and test the POC on Node ${{ matrix.node }} and ${{ matrix.os }}

    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Audit
        run: npm run audit-ci

      - name: Build
        run: npm run build
